---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
      containers:
        - image: quay.io/chmouel/go-simple-uploader
          volumeMounts:
            - mountPath: "/uploads"
              name: cache
          env:
            - name: UPLOADER_HOST
              value: "0.0.0.0"
            - name: UPLOADER_PORT
              value: "8080"
            - name: UPLOADER_DIRECTORY
              value: "/uploads"
          imagePullPolicy: Always
          name: simple-uploader
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: uploader
spec:
  selector:
    app: uploader
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
