---
apiVersion: v1
stringData:
  # Change this
  credentials: username:password
kind: Secret
metadata:
  name: uploader-upload-credentials
type: Opaque

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
      containers:
        - image: ghcr.io/chmouel/go-simple-uploader:master
          volumeMounts:
            - mountPath: "/uploads"
              name: cache
          env:
            - name: UPLOADER_HOST
              value: "0.0.0.0"
            - name: UPLOADER_PORT
              value: "8080"
            - name: UPLOADER_DIRECTORY
              value: "/uploads"
            - name: UPLOADER_UPLOAD_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: "uploader-upload-credentials"
                  key: "credentials"
          imagePullPolicy: Always
          name: simple-uploader
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: uploader
spec:
  selector:
    app: uploader
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-listener
